dofile("setupTests.lua")

describe("QuestState", function()
    local ns

    before_each(function()
        WowMock.Reset()
        ns = LoadAddon({ files = { "Modules/Database/Entries.lua", "Modules/Quest/QuestState.lua" } })
        ns.RegisterEntry({ id = "z", name = "Zone", category = "zones" })
        ns.AddQuests("z", { { id = 10, name = "First" }, { id = 11, name = "Second (2/3)" } })
    end)

    describe("QuestTitle", function()
        it("uses the client's title when it has one", function()
            WowMock.titles[10] = "Client title"
            assert.are.equal("Client title", ns.QuestTitle(10, "First"))
        end)
        it("otherwise the name in the data", function()
            assert.are.equal("First", ns.QuestTitle(10, "First"))
            assert.are.equal("Quest 99", ns.QuestTitle(99))
        end)
        it("keeps the step number of chains with repeated names", function()
            WowMock.titles[11] = "Second"
            assert.are.equal("Second (2/3)", ns.QuestTitle(11, "Second (2/3)"))
        end)
    end)

    describe("QuestStatus", function()
        it("done, in progress, available", function()
            WowMock.done[10] = true
            assert.are.equal("done", ns.QuestStatus({ id = 10 }))
            WowMock.onQuest[12] = true
            assert.are.equal("active", ns.QuestStatus({ id = 12 }))
            assert.are.equal("available", ns.QuestStatus({ id = 13 }))
        end)
        it("locked by level and by requirements, with the reasons", function()
            local status, reasons = ns.QuestStatus({ id = 20, minLevel = 30, requires = { 10 } })
            assert.are.equal("locked", status)
            assert.are.equal(2, #reasons)
            assert.matches("30", reasons[1])
            assert.matches("First", reasons[2])
        end)
        it("requiresAny: one done is enough", function()
            assert.are.equal("locked", (ns.QuestStatus({ id = 21, requiresAny = { 10, 11 } })))
            WowMock.done[11] = true
            assert.are.equal("available", (ns.QuestStatus({ id = 21, requiresAny = { 10, 11 } })))
        end)
    end)

    describe("level", function()
        it("low level: grey for the game", function()
            assert.is_true(ns.IsLowLevel({ level = 10 }))
            assert.is_false(ns.IsLowLevel({ level = 18 }))
            assert.is_false(ns.IsLowLevel({}))
        end)
        it("too high: can't be taken yet", function()
            assert.is_true(ns.IsTooHigh({ level = 21, minLevel = 21 }))
        end)
        it("too high: red for the game even with a low minimum (Master Angler)", function()
            assert.is_true(ns.IsTooHigh({ level = 60, minLevel = 1 }))
            assert.is_true(ns.IsTooHigh({ level = 25, minLevel = 1 }))
            assert.is_false(ns.IsTooHigh({ level = 24, minLevel = 1 }))
        end)
    end)

    describe("QuestVisible", function()
        before_each(function() ns.char = { filters = {} } end)

        it("hides other-faction quests unless the filter is on", function()
            assert.is_false(ns.QuestVisible({ faction = "Horde" }))
            ns.char.filters.otherFaction = true
            assert.is_true(ns.QuestVisible({ faction = "Horde" }))
        end)
        it("infers the faction from the races", function()
            assert.are.equal("Horde", ns.QuestFaction({ races = 2 + 16 }))
            assert.are.equal("Alliance", ns.QuestFaction({ races = 1 + 4 }))
            assert.is_nil(ns.QuestFaction({ races = 1 + 2 }))
        end)
        it("hides other-class quests unless looking at the classes section", function()
            assert.is_false(ns.QuestVisible({ classes = 1 }))          -- warrior (the player is a mage)
            assert.is_true(ns.QuestVisible({ classes = 128 }))         -- mage
            assert.is_true(ns.QuestVisible({ classes = 1 }, { category = "classes" }))
        end)
        it("hides other-race quests of your faction unless looking at the races section", function()
            assert.is_false(ns.QuestVisible({ races = 4 }))            -- dwarf (the player is human)
            assert.is_true(ns.QuestVisible({ races = 4 }, { category = "races" }))
        end)
        it("the ones marked hidden are never seen", function()
            assert.is_false(ns.QuestVisible({ hidden = true }))
        end)
    end)

    describe("QuestDescription", function()
        it("uses the data's text and puts in the character's name", function()
            assert.are.equal("Hello Tester", ns.QuestDescription({ id = 30, desc = "Hello $N" }))
            assert.is_nil(ns.QuestDescription({ id = 31 }))
        end)
        it("with the quest in the log reads the game's text and leaves the selection as it was", function()
            WowMock.onQuest[32] = true
            WowMock.selectedQuest = 5
            _G.GetQuestLogQuestText = function() return WowMock.selectedQuest == 32 and "Game text" or "" end
            assert.are.equal("Game text", ns.QuestDescription({ id = 32, desc = "english" }))
            assert.are.equal(5, WowMock.selectedQuest)
        end)
    end)
end)
