dofile("setupTests.lua")

describe("QuestState", function()
    local ns

    before_each(function()
        WowMock.Reset()
        ns = LoadAddon({ files = { "Modules/Database/Entries.lua", "Modules/Quest/QuestState.lua" } })
        ns.RegisterEntry({ id = "z", name = "Zone", category = "zones" })
        ns.AddQuests("z", { { id = 10, name = "First" }, { id = 11, name = "Second (2/3)" } })
    end)

    describe("QuestTitle", function()
        it("usa el titulo del cliente si lo tiene", function()
            WowMock.titles[10] = "Primera"
            assert.are.equal("Primera", ns.QuestTitle(10, "First"))
        end)
        it("si no, el nombre de los datos", function()
            assert.are.equal("First", ns.QuestTitle(10, "First"))
            assert.are.equal("Quest 99", ns.QuestTitle(99))
        end)
        it("conserva el numero de paso de las cadenas con nombres repetidos", function()
            WowMock.titles[11] = "Segunda"
            assert.are.equal("Segunda (2/3)", ns.QuestTitle(11, "Second (2/3)"))
        end)
    end)

    describe("QuestStatus", function()
        it("hecha, en curso, disponible", function()
            WowMock.done[10] = true
            assert.are.equal("done", ns.QuestStatus({ id = 10 }))
            WowMock.onQuest[12] = true
            assert.are.equal("active", ns.QuestStatus({ id = 12 }))
            assert.are.equal("available", ns.QuestStatus({ id = 13 }))
        end)
        it("bloqueada por nivel y por requisitos, con las razones", function()
            local status, reasons = ns.QuestStatus({ id = 20, minLevel = 30, requires = { 10 } })
            assert.are.equal("locked", status)
            assert.are.equal(2, #reasons)
            assert.matches("30", reasons[1])
            assert.matches("First", reasons[2])
        end)
        it("requiresAny: basta con una hecha", function()
            assert.are.equal("locked", (ns.QuestStatus({ id = 21, requiresAny = { 10, 11 } })))
            WowMock.done[11] = true
            assert.are.equal("available", (ns.QuestStatus({ id = 21, requiresAny = { 10, 11 } })))
        end)
    end)

    describe("nivel", function()
        it("bajo nivel: gris para el juego", function()
            assert.is_true(ns.IsLowLevel({ level = 10 }))
            assert.is_false(ns.IsLowLevel({ level = 18 }))
            assert.is_false(ns.IsLowLevel({}))
        end)
        it("demasiado alto: aun no se puede coger", function()
            assert.is_true(ns.IsTooHigh({ level = 21, minLevel = 21 }))
        end)
        it("demasiado alto: roja para el juego aunque el minimo sea bajo (Master Angler)", function()
            assert.is_true(ns.IsTooHigh({ level = 60, minLevel = 1 }))
            assert.is_true(ns.IsTooHigh({ level = 25, minLevel = 1 }))
            assert.is_false(ns.IsTooHigh({ level = 24, minLevel = 1 }))
        end)
    end)

    describe("QuestVisible", function()
        before_each(function() ns.char = { filters = {} } end)

        it("oculta las de otra faccion salvo con el filtro", function()
            assert.is_false(ns.QuestVisible({ faction = "Horde" }))
            ns.char.filters.otherFaction = true
            assert.is_true(ns.QuestVisible({ faction = "Horde" }))
        end)
        it("deduce la faccion de las razas", function()
            assert.are.equal("Horde", ns.QuestFaction({ races = 2 + 16 }))
            assert.are.equal("Alliance", ns.QuestFaction({ races = 1 + 4 }))
            assert.is_nil(ns.QuestFaction({ races = 1 + 2 }))
        end)
        it("oculta las de otra clase salvo mirando la seccion de clases", function()
            assert.is_false(ns.QuestVisible({ classes = 1 }))          -- guerrero (el jugador es mago)
            assert.is_true(ns.QuestVisible({ classes = 128 }))         -- mago
            assert.is_true(ns.QuestVisible({ classes = 1 }, { category = "classes" }))
        end)
        it("oculta las de otra raza de tu faccion salvo mirando la seccion de razas", function()
            assert.is_false(ns.QuestVisible({ races = 4 }))            -- enano (el jugador es humano)
            assert.is_true(ns.QuestVisible({ races = 4 }, { category = "races" }))
        end)
        it("las marcadas como ocultas no se ven nunca", function()
            assert.is_false(ns.QuestVisible({ hidden = true }))
        end)
    end)

    describe("QuestDescription", function()
        it("usa el texto de los datos y pone el nombre del personaje", function()
            assert.are.equal("Hola Tester", ns.QuestDescription({ id = 30, desc = "Hola $N" }))
            assert.is_nil(ns.QuestDescription({ id = 31 }))
        end)
        it("con la quest en el registro lee el texto del juego y deja la seleccion como estaba", function()
            WowMock.onQuest[32] = true
            WowMock.selectedQuest = 5
            _G.GetQuestLogQuestText = function() return WowMock.selectedQuest == 32 and "Texto del juego" or "" end
            assert.are.equal("Texto del juego", ns.QuestDescription({ id = 32, desc = "english" }))
            assert.are.equal(5, WowMock.selectedQuest)
        end)
    end)
end)
