// Usage: node tools/questie_forever.mjs
// Generates the quest data of Data/Generated/ from Questie's Forever database (see questie_db.mjs; set
// QUESTIEDB_TOC if Questie is somewhere else): Classic.lua (dungeons, raids and battlegrounds), Zones.lua,
// Classes.lua, Races.lua, Professions.lua, Extra.lua (events and miscellaneous) and Entrances.lua.
// Questie's Forever database already has its own corrections applied and its map points in Forever
// coordinates, so nothing is converted here.
//
//  * A quest belongs to an instance when its zone is the instance, or when an NPC that only ever spawns
//    inside it gives, receives or is the target of the quest; its prerequisite chain (up to 12 steps back)
//    and continuations (3 steps forward) come along.
//  * Zones, classes, professions and races get every other quest; the rest of Questie's quest sorts become
//    the Events and Miscellaneous entries.
import { writeFileSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { quest, npc, item, object, allIds, tocDir, keyed } from "./questie_db.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const GEN = join(ROOT, "Data", "Generated");
const ZONES = join(tocDir, "support", "Forever", "Zones");
const HEADER = ["local _, ns = ...", "",
    "-- GENERATED by tools/questie_forever.mjs from Questie's Forever database.",
    "-- Do not edit by hand: use Data/Overrides.lua.", ""];

// addon entry id -> the instance's area id in Questie (support/Forever/Zones/dungeons.lua)
const INSTANCE_AREA = {
    rfc: 2437, wc: 718, vc: 1581, sfk: 209, bfd: 719, stk: 717, gnom: 721, rfk: 491,
    sm: 796, rfd: 722, ulda: 1337, zf: 1176, mara: 2100, st: 1477, brd: 1584,
    lbrs: 1583, dm: 2557, scho: 2057, strat: 2017, dt: 2257,
    ony: 2159, mc: 2717, bwl: 2677, aq20: 3429, aq40: 3428, naxx: 3456, zg: 1977,
    av: 2597, wsg: 3277, ab: 3358,
};
const CLASS_SORT = { [-61]: "WARLOCK", [-81]: "WARRIOR", [-82]: "SHAMAN", [-141]: "PALADIN", [-161]: "MAGE",
    [-162]: "ROGUE", [-261]: "HUNTER", [-262]: "PRIEST", [-263]: "DRUID" };
const CLASS_MASK = { 1: "WARRIOR", 2: "PALADIN", 4: "HUNTER", 8: "ROGUE", 16: "PRIEST", 64: "SHAMAN", 128: "MAGE", 256: "WARLOCK", 1024: "DRUID" };
const CLASS_NAME = { WARRIOR: "Warrior", PALADIN: "Paladin", HUNTER: "Hunter", ROGUE: "Rogue", PRIEST: "Priest",
    SHAMAN: "Shaman", MAGE: "Mage", WARLOCK: "Warlock", DRUID: "Druid" };
const CLASS_ORDER = ["WARRIOR", "PALADIN", "HUNTER", "ROGUE", "PRIEST", "SHAMAN", "MAGE", "WARLOCK", "DRUID"];
// professions: by Questie's sort (negative) or by the skill the quest requires; key = the game's skill line id
const PROF_SORT = { [-24]: 182, [-101]: 356, [-121]: 164, [-181]: 171, [-182]: 165, [-201]: 202, [-264]: 197, [-304]: 185, [-324]: 129 };
const PROF_NAME = { 164: "Blacksmithing", 165: "Leatherworking", 171: "Alchemy", 182: "Herbalism", 185: "Cooking", 186: "Mining",
    197: "Tailoring", 202: "Engineering", 333: "Enchanting", 356: "Fishing", 129: "First Aid", 393: "Skinning" };
const RACES = ["Human", "Orc", "Dwarf", "Night Elf", "Undead", "Tauren", "Gnome", "Troll"];
// the rest of Questie's quest sorts: entries of the Events and Miscellaneous sections
const SORT_ENTRIES = [
    { sort: -365, id: "aq_war", name: "Ahn'Qiraj War Effort", category: "events" },
    { sort: -22, id: "seasonal", name: "Seasonal", category: "events" },
    { sort: -366, id: "lunar", name: "Lunar Festival", category: "events" },
    { sort: -364, id: "darkmoon", name: "Darkmoon Faire", category: "events" },
    { sort: -369, id: "midsummer", name: "Midsummer Fire Festival", category: "events" },
    { sort: -284, id: "special", name: "Special", category: "events" },
    { sort: -368, id: "invasion", name: "Scourge Invasion", category: "events" },
    { sort: -367, id: "reputation", name: "Reputation", category: "misc" },
    { sort: -344, id: "legendary", name: "Legendary", category: "misc" },
    { sort: -1, id: "epic", name: "Epic", category: "misc" },
];
const UP_HOPS = 6 * 2, DOWN_HOPS = 3;
const MAX_SOURCES = 40, MAX_STEPS = 6;
const ALLIANCE = 77, HORDE = 178, ALL_RACES = 255;

const lua = (s) => `"${String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n")}"`;
const f1 = (v) => (Math.round(v * 10) / 10).toFixed(1);
// Questie's positional groups: an array (group i at index i-1) or a map keyed by the group number
const group = (x, i) => (Array.isArray(x) ? x[i - 1] : x?.[i]) ?? [];

// ----------------------------------------------------------------------------------------------------
// data
const quests = new Map();
for (const id of allIds("Quest")) quests.set(id, quest(id));
const pre = (q) => [...(q[12] ?? []), ...(q[13] ?? [])];

// instance areas (main id + alternates) and entrances
const areaOf = new Map(), entranceOf = new Map();
for (const line of readFileSync(join(ZONES, "dungeons.lua"), "utf8").split(/\r?\n/)) {
    const m = line.match(/^\s*\[(\d+)\] = \{"([^"]+)",(.*)$/);
    if (!m) continue;
    const id = Number(m[1]);
    areaOf.set(id, id);
    const alts = m[3].match(/^\{([^}]*)\}/);
    if (alts) for (const a of alts[1].match(/\d+/g) ?? []) areaOf.set(Number(a), id);
    const e = m[3].match(/,\s*\d+,\s*\{\s*\{\s*(\d+),\s*([\d.]+),\s*([\d.]+)/);
    if (e) entranceOf.set(id, { area: Number(e[1]), x: Number(e[2]), y: Number(e[3]) });
}
// zones with a map in Classic (uiMapId 1411..1459) and their names; subzones -> their zone
const zoneName = new Map();
for (const line of readFileSync(join(ZONES, "uiMapIdToAreaId.lua"), "utf8").split(/\r?\n/)) {
    const m = line.match(/^\s*\[(\d+)\]\s*=\s*(\d+),\s*--\s*(.*?)\s*$/);
    if (m && Number(m[1]) >= 1411 && Number(m[1]) <= 1459 && Number(m[2]) > 0 && Number(m[2]) < 10000) zoneName.set(Number(m[2]), m[3]);
}
zoneName.delete(2597); // Alterac Valley: a battleground
const parent = new Map([[9, 12], [132, 1], [188, 141], [154, 85], [363, 14], [220, 215]]);
for (const line of readFileSync(join(ZONES, "subZoneToParentZone.lua"), "utf8").split(/\r?\n/)) {
    const m = line.match(/^\s*\[(\d+)\]\s*=\s*(\d+),/);
    if (m && !parent.has(Number(m[1]))) parent.set(Number(m[1]), Number(m[2]));
}

// ----------------------------------------------------------------------------------------------------
// which quests belong to each instance
// an NPC "belongs" to an instance if all its spawn zones are that instance's
function npcInstance(npcId) {
    const spawns = keyed(npc(npcId)?.[7]);
    if (!Object.keys(spawns).length) return null;
    let inst = null;
    for (const zone of Object.keys(spawns)) {
        const d = areaOf.get(Number(zone));
        if (!d || (inst && inst !== d)) return null;
        inst = d;
    }
    return inst;
}
function instancesOf(q) {
    const found = new Set();
    const add = (d) => { if (d) found.add(d); };
    add(areaOf.get(q[17]));
    for (const id of group(q[2], 1)) add(npcInstance(id));
    for (const id of group(q[3], 1)) add(npcInstance(id));
    for (const o of group(q[10], 1)) add(npcInstance(o[0]));
    return found;
}
const core = new Map(), children = new Map();
const push = (map, k, v) => { if (!map.has(k)) map.set(k, []); map.get(k).push(v); };
for (const [id, q] of quests) {
    for (const d of instancesOf(q)) { if (!core.has(d)) core.set(d, new Set()); core.get(d).add(id); }
    for (const p of pre(q)) push(children, p, id);
}
for (const [id, q] of quests) if (q[22] && quests.has(q[22])) push(children, id, q[22]);

// prerequisites: up to UP_HOPS steps back; continuations: DOWN_HOPS forward (further on, chains from other
// zones creep in, e.g. Argent Dawn from Stratholme); it never crosses into another instance's own quests
function collect(area) {
    const set = new Set(core.get(area) ?? []);
    const foreign = (id) => [...core].some(([d, ids]) => d !== area && ids.has(id));
    const walk = (neighbours, maxHops) => {
        let frontier = [...(core.get(area) ?? [])];
        for (let hop = 0; hop < maxHops; hop++) {
            const next = [];
            for (const id of frontier) {
                for (const n of neighbours(id)) {
                    if (quests.has(n) && !set.has(n) && !foreign(n)) { set.add(n); next.push(n); }
                }
            }
            if (!next.length) break;
            frontier = next;
        }
    };
    walk((id) => pre(quests.get(id)), UP_HOPS);
    walk((id) => children.get(id) ?? [], DOWN_HOPS);
    return set;
}

// ----------------------------------------------------------------------------------------------------
// masks: the quest's own or, if it has none, the one inherited from its mandatory prerequisites
// (intersection), so a quest that needs a Horde-only or class-only quest is Horde-only or class-only too
function inheritedMask(field) {
    const memo = new Map();
    const mask = (id, depth) => {
        if (memo.has(id)) return memo.get(id);
        memo.set(id, false); // cuts cycles
        const q = quests.get(id);
        if (!q) return false;
        let m = q[field] || null;
        if (m === ALL_RACES && field === 6) m = null;
        if (!m && depth < 30) {
            const parents = [...(q[12] ?? [])];
            if ((q[13] ?? []).length === 1) parents.push(q[13][0]);
            for (const p of parents) {
                const pm = mask(p, depth + 1);
                if (pm) m = m ? (m & pm) : pm;
            }
            if (m === 0) m = null;
        }
        memo.set(id, m || false);
        return memo.get(id);
    };
    return (id) => mask(id, 0) || null;
}
const classMask = inheritedMask(7), raceMask = inheritedMask(6);

// Whether the quest is done inside the instance. Questie also files under a dungeon the quests of its quest
// line that never go in (the druids' chain to Wailing Caverns is all in the Barrens and Thunder Bluff), so a
// dungeon quest is only marked when it starts or ends inside, or has something to do there; a quest with
// nothing but talking, or whose targets are all known to be outside, is not. When the data can't say where
// an objective is (an item with no known dropper, e.g. the Egg of Hakkar), it is kept marked. Raids and
// battlegrounds are done inside by definition: every quest of theirs is marked.
const INSIDE_ALL = new Set(["ony", "mc", "bwl", "aq20", "aq40", "naxx", "zg", "av", "wsg", "ab", "dt"]);
const inInstance = (zone, area) => areaOf.get(zone) === area || areaOf.get(parent.get(zone)) === area;
// where some spawns are: "inside", "outside" or "unknown" (no spawn data)
function spawnClass(spawns, area) {
    const zones = Object.keys(keyed(spawns)).map(Number);
    if (!zones.length) return "unknown";
    return zones.some((z) => inInstance(z, area)) ? "inside" : "outside";
}
// where an item comes from: the mobs and objects that drop it
function itemClass(itemId, area) {
    const it = item(itemId);
    const sources = [...(it?.[2] ?? []).map((id) => spawnClass(npc(id)?.[7], area)), ...(it?.[3] ?? []).map((id) => spawnClass(object(id)?.[4], area))];
    if (sources.includes("inside")) return "inside";
    return sources.some((s) => s === "outside") ? "outside" : "unknown";
}
function doneInside(q, area, entry) {
    if (INSIDE_ALL.has(entry)) return true;
    const starts = q[2], ends = q[3], obj = q[10];
    if (group(starts, 1).some((id) => npcInstance(id) === area) || group(ends, 1).some((id) => npcInstance(id) === area)) return true;
    const classes = [
        ...group(starts, 2).map((id) => spawnClass(object(id)?.[4], area)),
        ...group(starts, 3).map((id) => itemClass(id, area)),
        ...group(ends, 2).map((id) => spawnClass(object(id)?.[4], area)),
        ...group(obj, 1).map((o) => spawnClass(npc(o[0])?.[7], area)),
        ...group(obj, 2).map((o) => spawnClass(object(o[0])?.[4], area)),
        ...group(obj, 3).map((o) => itemClass(o[0], area)),
        ...group(obj, 5).map((o) => ((o[0] ?? []).some((id) => spawnClass(npc(id)?.[7], area) === "inside") ? "inside" : "outside")),
    ];
    const trigger = q[9];
    if (Array.isArray(trigger) && trigger[1]) classes.push(Object.keys(keyed(trigger[1])).some((z) => inInstance(Number(z), area)) ? "inside" : "outside");
    return classes.includes("inside") || classes.includes("unknown");
}

// quests done inside one of our instances: marked dungeon = "<entry id>", also when they show in a zone
const ENTRY_OF_AREA = new Map(Object.entries(INSTANCE_AREA).map(([e, a]) => [a, e]));
const dungeonOf = new Map();
for (const [area, ids] of core) {
    const entry = ENTRY_OF_AREA.get(area);
    if (!entry) continue;
    for (const id of ids) {
        if (!doneInside(quests.get(id), area, entry)) continue;
        if (!dungeonOf.has(id) || entry < dungeonOf.get(id)) dungeonOf.set(id, entry);
    }
}
// ----------------------------------------------------------------------------------------------------
// locations and steps
// an NPC's location: preferred zone (its most common) and first coordinate; NPCs inside an instance have
// coordinates -1 and are emitted without a position
function location(npcId) {
    const n = npc(npcId);
    const parts = [`npc = ${lua(n[1])}`];
    const spawns = keyed(n[7]);
    if (Object.keys(spawns).length) {
        const zone = spawns[n[9]] ? n[9] : Math.min(...Object.keys(spawns).map(Number));
        const c = spawns[zone]?.[0];
        if (c && c[0] >= 0) parts.push(`area = ${zone}`, `x = ${f1(c[0])}`, `y = ${f1(c[1])}`);
    }
    return `{ ${parts.join(", ")} }`;
}

// the densest spot of a cloud of points: the 6x6 cell (with its neighbors) holding the most
function densest(pts) {
    const CELL = 6, grid = new Map(), cells = [];
    const cell = (v) => Math.floor(v / CELL);
    const key = (i, j) => i * 1000 + j;
    for (const [x, y] of pts) {
        const k = key(cell(x), cell(y));
        if (!grid.has(k)) { grid.set(k, 0); cells.push([cell(x), cell(y)]); }
        grid.set(k, grid.get(k) + 1);
    }
    let best, bestN = -1;
    for (const [i, j] of cells) {
        let n = 0;
        for (let di = -1; di <= 1; di++) for (let dj = -1; dj <= 1; dj++) n += grid.get(key(i + di, j + dj)) ?? 0;
        if (n > bestN) { best = [i, j]; bestN = n; }
    }
    const near = pts.filter(([x, y]) => Math.abs(cell(x) - best[0]) <= 1 && Math.abs(cell(y) - best[1]) <= 1);
    return [near.reduce((s, p) => s + p[0], 0) / near.length, near.reduce((s, p) => s + p[1], 0) / near.length];
}

function stepFrom(name, byZone) {
    if (!name) return null;
    let bestZone, bestPts;
    for (const [zone, pts] of Object.entries(byZone)) {
        if (!bestPts || pts.length > bestPts.length || (pts.length === bestPts.length && Number(zone) < Number(bestZone))) { bestZone = zone; bestPts = pts; }
    }
    if (!bestPts) return null;
    const valid = bestPts.filter((c) => c[0] >= 0);
    if (!valid.length) return `{ name = ${lua(name)}, area = ${areaOf.get(Number(bestZone)) ?? bestZone} }`; // inside an instance
    const [x, y] = densest(valid);
    return `{ name = ${lua(name)}, area = ${bestZone}, x = ${f1(x)}, y = ${f1(y)} }`;
}
const addSpawns = (acc, spawns) => { for (const [zone, list] of Object.entries(keyed(spawns))) (acc[zone] ??= []).push(...list); };

// one step per objective: kill, world object, collect an item (from its droppers), kill credit, event
function stepsOf(q) {
    const steps = [];
    const add = (s) => { if (s && steps.length < MAX_STEPS) steps.push(s); };
    const obj = q[10];
    for (const o of group(obj, 1)) { const n = npc(o[0]); if (n) { const acc = {}; addSpawns(acc, n[7]); add(stepFrom(o[1] || n[1], acc)); } }
    for (const o of group(obj, 2)) { const ob = object(o[0]); if (ob) { const acc = {}; addSpawns(acc, ob[4]); add(stepFrom(o[1] || ob[1], acc)); } }
    for (const o of group(obj, 3)) {
        const it = item(o[0]);
        if (!it) continue;
        const acc = {};
        let used = 0;
        for (const id of it[2] ?? []) if (used < MAX_SOURCES && npc(id)) { addSpawns(acc, npc(id)[7]); used++; }
        for (const id of it[3] ?? []) if (used < MAX_SOURCES && object(id)) { addSpawns(acc, object(id)[4]); used++; }
        add(stepFrom(it[1], acc));
    }
    for (const o of group(obj, 5)) { // kill credit: { {npcs}, base npc, text }
        const acc = {};
        for (const id of o[0] ?? []) if (npc(id)) addSpawns(acc, npc(id)[7]);
        add(stepFrom(o[2] || npc(o[1])?.[1], acc));
    }
    const trigger = q[9];
    if (Array.isArray(trigger) && trigger[1]) add(stepFrom(trigger[0], keyed(trigger[1])));
    return steps;
}

// ----------------------------------------------------------------------------------------------------
// quest lines
// chain steps that share a name and races inside an entry are numbered in chain order: "Name (2/7)"
function displayNames(set) {
    const depth = new Map();
    const depthOf = (id) => {
        if (depth.has(id)) return depth.get(id);
        depth.set(id, 0);
        let m = 0;
        for (const p of pre(quests.get(id))) if (set.has(p)) m = Math.max(m, depthOf(p) + 1);
        depth.set(id, m);
        return m;
    };
    const groups = new Map();
    for (const id of set) {
        const q = quests.get(id);
        const key = `${q[1]}|${q[6]}`;
        if (!groups.has(key)) groups.set(key, []);
        groups.get(key).push(id);
    }
    const names = new Map();
    for (const g of groups.values()) {
        g.sort((a, b) => depthOf(a) - depthOf(b) || a - b);
        g.forEach((id, i) => names.set(id, g.length > 1 ? `${quests.get(id)[1]} (${i + 1}/${g.length})` : quests.get(id)[1]));
    }
    return names;
}

// exact factions -> faction; other race restrictions -> races; class restrictions -> classes (except in
// class entries, where they are the reason for being there)
function questLine(id, name, comment, noClasses) {
    const q = quests.get(id);
    const f = [`id = ${id}`, `name = ${lua(name)}`];
    if (q[5] > 0) f.push(`level = ${q[5]}`);
    if (q[4] > 0) f.push(`minLevel = ${q[4]}`);
    const grp = (q[12] ?? []).filter((p) => p > 0);
    let single = (q[13] ?? []).filter((p) => p > 0);
    if (single.length === 1) { grp.push(single[0]); single = []; }
    if (grp.length) f.push(`requires = { ${grp.join(", ")} }`);
    if (single.length > 1) f.push(`requiresAny = { ${single.join(", ")} }`);
    const races = raceMask(id);
    if (races === ALLIANCE) f.push('faction = "Alliance"');
    else if (races === HORDE) f.push('faction = "Horde"');
    else if (races) f.push(`races = ${races}`);
    const classes = classMask(id);
    if (classes && !noClasses) f.push(`classes = ${classes}`);
    if (dungeonOf.has(id)) f.push(`dungeon = ${lua(dungeonOf.get(id))}`);
    const giver = group(q[2], 1)[0], finisher = group(q[3], 1)[0];
    if (giver && npc(giver)) { f.push(`giver = ${lua(npc(giver)[1])}`); f.push(`start = ${location(giver)}`); }
    if (finisher && npc(finisher)) f.push(`finish = ${location(finisher)}`);
    const steps = stepsOf(q);
    if (steps.length) f.push(`steps = { ${steps.join(", ")} }`);
    const text = (q[8] ?? []).join(" ");
    if (text.trim()) f.push(`objective = ${lua(text)}`);
    return `    { ${f.join(", ")} },${comment ?? ""}`;
}

// rough level of an entry: 10th percentile of the required level and 90th of the quest level
function levelRange(set) {
    const req = [], lvl = [];
    for (const id of set) {
        const q = quests.get(id);
        if (q[4] > 0) req.push(q[4]);
        if (q[5] > 0) lvl.push(q[5]);
    }
    req.sort((a, b) => a - b); lvl.sort((a, b) => a - b);
    const lo = req[Math.max(1, Math.ceil(req.length * 0.1)) - 1] ?? 1;
    const hi = lvl[Math.max(1, Math.ceil(lvl.length * 0.9)) - 1] ?? lo;
    return [lo, Math.max(lo, hi)];
}

function emitEntry(out, entryId, header, set, noClasses, commentOf) {
    const sorted = [...set].sort((a, b) => a - b);
    const names = displayNames(set);
    if (header) out.push(header);
    out.push(`ns.AddQuests(${lua(entryId)}, {`);
    for (const id of sorted) out.push(questLine(id, names.get(id), commentOf?.(id), noClasses));
    out.push("})", "");
    return sorted.length;
}
const write = (file, lines) => writeFileSync(join(GEN, file), lines.join("\n") + "\n");

// ----------------------------------------------------------------------------------------------------
// Classic.lua: instances
const classic = [...HEADER];
const instSummary = [];
for (const [entry, area] of Object.entries(INSTANCE_AREA)) {
    const set = collect(area);
    if (!set.size) continue;
    const coreSet = core.get(area) ?? new Set();
    const n = emitEntry(classic, entry, null, set, false, (id) => (coreSet.has(id) ? "" : " -- chain"));
    instSummary.push(`${entry} ${n} (${coreSet.size} core)`);
}
write("Classic.lua", classic);

// ----------------------------------------------------------------------------------------------------
// zones, classes, professions, races
const zoneSet = new Map(), classSet = new Map(), profSet = new Map();
const put = (map, k, id) => { if (!map.has(k)) map.set(k, new Set()); map.get(k).add(id); };
for (const [id, q] of quests) {
    const z = q[17] ?? 0;
    const skill = PROF_SORT[z] ?? (q[18] && PROF_NAME[q[18][0]] ? q[18][0] : null);
    if (skill) put(profSet, skill, id);
    const cls = CLASS_SORT[z] ?? CLASS_MASK[classMask(id) ?? 0];
    if (cls) put(classSet, cls, id);
    else if (z > 0 && !areaOf.has(z)) {
        const area = zoneName.has(z) ? z : parent.get(z);
        if (area && zoneName.has(area)) put(zoneSet, area, id);
    }
}

const zout = [...HEADER];
const zones = [...zoneSet].map(([area, set]) => ({ area, name: zoneName.get(area), set, range: levelRange(set) }));
zones.sort((a, b) => a.range[0] - b.range[0] || (a.name < b.name ? -1 : 1));
let totalZ = 0;
for (const z of zones) {
    totalZ += emitEntry(zout, `z${z.area}`,
        `ns.RegisterEntry({ id = ${lua("z" + z.area)}, name = ${lua(z.name)}, category = "zones", area = ${z.area}, minLevel = ${z.range[0]}, maxLevel = ${z.range[1]} })`, z.set);
}
write("Zones.lua", zout);

const cout = [...HEADER];
let totalC = 0;
for (const cls of CLASS_ORDER) {
    if (!classSet.has(cls)) continue;
    totalC += emitEntry(cout, `c_${cls}`,
        `ns.RegisterEntry({ id = ${lua("c_" + cls)}, name = ${lua(CLASS_NAME[cls])}, category = "classes", classFile = ${lua(cls)} })`, classSet.get(cls), true);
}
write("Classes.lua", cout);

const pout = [...HEADER];
let totalP = 0;
for (const skill of [...profSet.keys()].sort((a, b) => (PROF_NAME[a] < PROF_NAME[b] ? -1 : 1))) {
    const [lo, hi] = levelRange(profSet.get(skill));
    totalP += emitEntry(pout, `p_${skill}`,
        `ns.RegisterEntry({ id = ${lua("p_" + skill)}, name = ${lua(PROF_NAME[skill])}, category = "professions", skillLine = ${skill}, minLevel = ${lo}, maxLevel = ${hi} })`, profSet.get(skill));
}
write("Professions.lua", pout);

// races: quests of one or a few races (not of a whole faction) also appear in the entry of each race
// included; in the zones only members of that race see them
const raceSet = new Map();
for (const set of zoneSet.values()) {
    for (const id of set) {
        const m = raceMask(id);
        if (!m || m === ALLIANCE || m === HORDE) continue;
        const bits = [];
        for (let bit = 0; bit < 8; bit++) if ((m >> bit) & 1) bits.push(bit + 1);
        if (bits.length <= 3) for (const r of bits) put(raceSet, r, id);
    }
}
const rout = [...HEADER];
let totalR = 0;
RACES.forEach((name, i) => {
    if (raceSet.has(i + 1)) totalR += emitEntry(rout, `r_${i + 1}`,
        `ns.RegisterEntry({ id = ${lua("r_" + (i + 1))}, name = ${lua(name)}, category = "races", raceId = ${i + 1} })`, raceSet.get(i + 1));
});
write("Races.lua", rout);

// events and miscellaneous: the other quest sorts
const eout = [...HEADER];
let totalE = 0;
for (const e of SORT_ENTRIES) {
    const set = new Set([...quests].filter(([, q]) => q[17] === e.sort).map(([id]) => id));
    if (!set.size) continue;
    totalE += emitEntry(eout, e.id, `ns.RegisterEntry({ id = ${lua(e.id)}, name = ${lua(e.name)}, category = ${lua(e.category)} })`, set);
}
write("Extra.lua", eout);

// entrances of the instances (parent zone + the portal's coordinates)
const ent = ["local _, ns = ...", "", "-- GENERATED by tools/questie_forever.mjs (Questie's Forever dungeons.lua). Do not edit by hand.", ""];
for (const entry of Object.keys(INSTANCE_AREA).sort()) {
    const e = entranceOf.get(INSTANCE_AREA[entry]);
    if (e) ent.push(`ns.SetEntrance(${lua(entry)}, { area = ${e.area}, x = ${f1(e.x)}, y = ${f1(e.y)} })`);
}
write("Entrances.lua", ent);

console.log("instances:", instSummary.join("  "));
console.log(`zones: ${zones.length} entries, ${totalZ} quests; classes ${totalC}; professions ${totalP}; races ${totalR}; events/misc ${totalE}`);
